baseURL = "http://memorandum.always-basics.com/"
languageCode = "en-us"
title = "Memorandum - Danger past, god forgotten"
theme = "erblog"
paginate = 5
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

# Google Analytics
googleAnalytics = "UA-75025058-6"

[params]
    author = "Always Basics"
    badge = "red"
    quote = "blue"
    index_posts_num = 8
    google_search = true
    logo = "/images/logo.jpg"
    portrait = "/images/logo.jpg"
    bio = """
    <p> 継続する秘訣は、途切れたと思った時にもう一度繰り返すこと</p>
    <br />
    """
    # copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."

[[menu.main]]
    identifier = "programming"
    name = "Programming"
    url = "/categories/programming/"
    weight = 1
[[menu.main]]
    identifier = "hugo"
    name = "Hugo"
    url = "/categories/web/"
    weight = 2
[[menu.main]]
    identifier = "theia"
    name = "Theia"
    url = "/categories/theia/"
    weight = 3
[[menu.main]]
    identifier = "electronic_kit"
    name = "電子工作"
    url = "/categories/電子工作/"
    weight = 4
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[[menu.footer]]
    identifier = "python"
    name = "Pythonなら空も飛べるはず"
    url = "https://python.always-basics.com/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
    category = "categories"
    tag = "tags"
    # series = "series"

[[menu.icon]]
    url = "https://github.com/kzthrk/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "mailto:kzthrk@gmail.com"
    name = "envelope-o"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/Always_Basics"
    name = "twitter"
    weight = 3

# [[menu.icon]]
#     url = "https://www.instagram.com/username/"
#     name = "instagram"
#     weight = 4
